In [1]:
import numpy as np

In [38]:
'''
calculate the pairwise subtraction between the rows of these two arrays
Are you able to do this without using loops?
let us say we have 2 2-d array, I want to substract each row in a from every row in b without using loops.
'''
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
b = np.arange(6, 6+6).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

## for loop method

In [48]:
def distance_cal(a, b):
    result = np.empty((a.shape[0], b.shape[0], a.shape[1]))
    for i, row_a in enumerate(a):
        for j, row_b in enumerate(b):
            result[i, j] = row_a - row_b
    return result

In [61]:
'''
the result is in a shape of (4, 2, 3) 
4 = the number of row in a
2 = the number of row in b
3 = the number of col in a or b (cause they are the same)
'''
distance_cal(a, b)

array([[[-6., -6., -6.],
        [-9., -9., -9.]],

       [[-3., -3., -3.],
        [-6., -6., -6.]],

       [[ 0.,  0.,  0.],
        [-3., -3., -3.]],

       [[ 3.,  3.,  3.],
        [ 0.,  0.,  0.]]])

## End for loop method

In [59]:
'''
numpy broadcasting
we have a (3,) array minus a (2,3) array
what numpy will do is:
it will apply substraction between each row in (2,3) with (3,)
'''
np.array([0, 1, 2]) - np.array([[6,7,8],
                                [9,10,11]])

array([[-6, -6, -6],
       [-9, -9, -9]])

In [52]:
'''
now we can use the same idea in 2d array
original shape of a is (4, 3)
new shape of a is (4, 1, 3)
we can think of 3d array like this
the first axis is: how many (1,3) sheets we have (in this example we have 4 samples)
the second axis is the row 
the third axis is the col
'''
a[:, np.newaxis] # you can also use reshape method 

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [56]:
'new shape of b is (1, 2, 3)'
b[np.newaxis]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [64]:
'''
what we are doing here is:
we have 4 samples in a, each one of them is (1, 3)
we have 1 sample in b which is (2, 3)
numpy will apply substraction on each (1, 3) in a with the (2, 3) in b
'''
c = a[:, np.newaxis] - b[np.newaxis]
c

array([[[-6, -6, -6],
        [-9, -9, -9]],

       [[-3, -3, -3],
        [-6, -6, -6]],

       [[ 0,  0,  0],
        [-3, -3, -3]],

       [[ 3,  3,  3],
        [ 0,  0,  0]]])

In [65]:
'''
euclidean distance
'''
c.sum(axis = 2)

array([[-18, -27],
       [ -9, -18],
       [  0,  -9],
       [  9,   0]])

In [67]:
'''
euclidean distance
each row represents a sample from a
each col represents a sample from b
the final result is a 4 by 2 matrix
'''
np.sqrt(c.sum(axis = 2)**2)

array([[18., 27.],
       [ 9., 18.],
       [ 0.,  9.],
       [ 9.,  0.]])